name: Test
on: push
jobs:
    launch:
        name: Launch
        runs-on: ubuntu-latest
        container: node:17.6.0
        steps:
            - run: node --version
            - run: npm --version